### ISSUE TITLE
Data in point1k.tsv

### ISSUE THREAD

**Issue by ChenZhongPu** [syoummer/SpatialSpark#3]
each line in `point1k.tsv` is the the fomat of 

```
609053316   POINT(971140.000000 200770.000000)
```

what is the meaning of `609053316`?

**Comment by syoummer** [comment]
it is an unique id for each point. 

Date: Fri, 20 Mar 2015 23:42:22 -0700

**Comment by varpande** [comment]
Hi which spatial reference format is the data in?

**Comment by syoummer** [comment]
It's 2263, local projection in NYC area.
