### ISSUE TITLE
generatePartitions function in STIndex.scala

### ISSUE THREAD

**Issue by ChenZhongPu** [syoummer/SpatialSpark#5]
I have several questions.

```
//sort by center_x, slice, center_y
    val centroids = sampleData.map(x => ((x.xmin + x.xmax) / 2.0, (x.ymin + x.ymax) / 2.0))
    val objs = centroids.sortByKey(true).zipWithIndex().map(x => (x._1._1, x._1._2, x._2))
    val objectsSorted = objs.map(x=>(Wrapped(x._3/numObjectsPerSlice, x._2), x))
      .sortByKey(true).values
```

`objs` is `RDD[(Double,Double.Long)]` and the third element is the index(Long).

then `Wrapped(x._3/numObjectsPerSlice, x._2)`, `x._3` should be the index(Long). Why should we build such a class,and sort by the `Wrapped`, which has something to do with the index(Long)?

**Comment by syoummer** [comment]
I want to sort the data inside each slice. 

BTW, if you have questions like this, not bug report or improvement suggestions. You may send me email directly rather than creating issues here :)
